server:
  port: 8080

#db configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=oppoStore;encrypt=true;trustServerCertificate=true;"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: spring
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 692742684673-ntqlvn9b4b153p0b4i2oc5fqf4ff2ndl.apps.googleusercontent.com
            client-secret: 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
        provider:
          google:
            issuer-uri: https://accounts.google.com
  mail:
    host: smtp.gmail.com
    port: 587
    username: vuhlong2610@gmail.com
    password: ojzlsupaywsivfun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "ZcCAeQKy0ly5bPdCVHM8bLQp5KJX9eczTqZl7zhjzK42U7SXfALZcWpSjitA5tLX"
  valid-duration: 36000 # in second .
  refreshable-duration: 360000 # in seconds .



